### Health Check
GET http://localhost:3000/health

### Health DB Check
GET http://localhost:3000/health/db

### Next Metro
GET http://localhost:3000/metro/next-metro?station=Chatelet

### Last Metro
GET http://localhost:3000/metro/last-metro?station=Chatelet

### Last Metro unknown station (with suggestion)
GET http://localhost:3000/metro/last-metro?station=chat

### Last Metro without station param
GET http://localhost:3000/metro/last-metro

### API Documentation
GET http://localhost:3000/api-docs